### ISSUE TITLE
SDK for python

### ISSUE THREAD

**Issue by gray-adeyi** [Easepay/easepay-sdk-rust#1]
I know this is not the right medium to reach out but it's all I have. I want to write the python sdk but the api reference is blank please can you point me to the docs i can use?

**Comment by opeolluwa** [comment]
Hi @gray-adeyi, thanks for reaching out, the API reference is under maintenance and will be made available shortly, do check back with us.

**Comment by gray-adeyi** [comment]
Okay thanks. Can I get notified. When it's up?

**Comment by Geoelycom** [comment]
hello @gray-adeyi can you please email HR with your CV @ careers@easepay.io
if we fancy your skills, we will reach out to you. the underlying API isn't open-source so it does create a restriction giving you access to build this.

**Comment by gray-adeyi** [comment]
Okay thanks
